name: studyflow_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.9
  animations: ^2.0.8
  flutter_foreground_task: ^9.1.0
  flutter_local_notifications: ^19.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.0
  flutter_localizations:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/IconoGrande.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/Icono2.png
  android: true
  ios: true
  android_12:
    image: assets/images/Icono2.png
    icon_background_color: "#ffffff"
